// Fencer intel lookup — fuzzy match by name → returns rich tactical data.
// Data scraped from fencingtracker.com, generated by foiliq-pipeline.
// 215 fencers covered (top-100 Y14 + top-100 Y12 nationally ranked, plus juniors).

// Per CLAUDE.md hard rule #7: fencer-name matching is case-INSENSITIVE always.
// Input may arrive in any case/order: "BIELER Mason", "Bieler, Mason",
// "Mason Bieler", "wang sicheng", "(27T) TSUI Raedyn Ho Hin".

let _data = null;
let _byFullName = null;   // Map normalized full-name (both orderings) → fencer
let _byLastname = null;   // Map lowercase lastname token → [fencers]

function tokenize(name) {
    if (!name) return [];
    return String(name)
        .replace(/\(.*?\)/g, ' ')          // strip "(27T)" seed prefix etc.
        .toLowerCase()
        .replace(/[,.]/g, ' ')              // commas/periods → spaces
        .replace(/[^a-z\s]/g, '')           // letters only
        .split(/\s+/)
        .filter(Boolean);
}

async function load() {
    if (_data) return _data;
    try {
        const r = await fetch('./js/lib/fencer-intel.json');
        _data = await r.json();
        _byFullName = new Map();
        _byLastname = new Map();
        for (const f of _data) {
            const tokens = tokenize(f.name);
            if (!tokens.length) continue;
            // intel.json uses "Lastname, Firstname" — after tokenize() the first
            // token is the lastname.
            const lastname = tokens[0];
            if (!_byLastname.has(lastname)) _byLastname.set(lastname, []);
            _byLastname.get(lastname).push(f);
            // Also register every order permutation as a full-name key
            _byFullName.set(tokens.join(' '), f);                          // last first ...
            _byFullName.set([...tokens.slice(1), tokens[0]].join(' '), f); // first ... last
        }
        return _data;
    } catch (e) {
        console.warn('fencer-intel load fail', e);
        _data = []; _byFullName = new Map(); _byLastname = new Map();
        return [];
    }
}

export async function getIntel(opponentName) {
    await load();
    if (!opponentName) return null;
    const tokens = tokenize(opponentName);
    if (!tokens.length) return null;

    // Try exact full-name in both orderings
    if (_byFullName.has(tokens.join(' '))) return _byFullName.get(tokens.join(' '));
    const reversed = [...tokens.slice(1), tokens[0]].join(' ');
    if (_byFullName.has(reversed)) return _byFullName.get(reversed);

    // Try lastname-only — first token OR last token (handles both orderings)
    for (const candidate of [tokens[0], tokens[tokens.length - 1]]) {
        if (!_byLastname.has(candidate)) continue;
        const matches = _byLastname.get(candidate);
        if (matches.length === 1) return matches[0];
        // Multiple fencers with same lastname — disambiguate by any firstname token overlap
        const firstNameSet = new Set(tokens.filter(t => t !== candidate));
        for (const m of matches) {
            const mTokens = tokenize(m.name);
            if (mTokens.some(t => firstNameSet.has(t))) return m;
        }
        return matches[0];  // fall back to first
    }
    return null;
}

export async function searchIntel(query) {
    await load();
    if (!query || query.length < 2) return [];
    const q = query.toLowerCase().trim();
    return (_data || []).filter(f => f.name.toLowerCase().includes(q)).slice(0, 10);
}

/**
 * Return the national-ranking roster for a profile role.
 *   raedyn → all Y14-ranked fencers sorted by Y14 rank
 *   kaylan → all Y12-ranked fencers sorted by Y12 rank
 * Each entry is the full intel record.
 */
export async function getNationalRoster(role) {
    await load();
    if (!_data) return [];
    const rankKey = role === 'raedyn' ? 'y14' : role === 'kaylan' ? 'y12' : null;
    if (!rankKey) return [];
    return _data
        .filter(f => (f.ranks || {})[rankKey])
        .sort((a, b) => a.ranks[rankKey] - b.ranks[rankKey]);
}

export function getRosterRankKey(role) {
    return role === 'raedyn' ? 'y14' : role === 'kaylan' ? 'y12' : null;
}
