// Fencer intel lookup — fuzzy match by name → returns rich tactical data.
// Data scraped from fencingtracker.com, generated by foiliq-pipeline.
// 215 fencers covered (top-100 Y14 + top-100 Y12 nationally ranked, plus juniors).

let _data = null;
let _byNorm = null;

function normalize(name) {
    if (!name) return '';
    // "BIELER Mason" / "Bieler, Mason" / "Mason Bieler" — normalize to lastname-first lowercase compact
    let s = name.toLowerCase().trim()
        .replace(/\(.*?\)/g, '')                    // remove parens
        .replace(/[^a-z\s,]/g, '')                   // letters + commas only
        .replace(/\s+/g, ' ').trim();
    if (s.includes(',')) {
        const [last, first] = s.split(',').map(x => x.trim());
        return `${last} ${first}`.trim();
    }
    // "First Last" → last first
    const parts = s.split(' ');
    if (parts.length >= 2) return `${parts[parts.length-1]} ${parts.slice(0, -1).join(' ')}`;
    return s;
}

async function load() {
    if (_data) return _data;
    try {
        const r = await fetch('./js/lib/fencer-intel.json');
        _data = await r.json();
        _byNorm = new Map();
        for (const f of _data) {
            _byNorm.set(normalize(f.name), f);
        }
        return _data;
    } catch (e) { console.warn('fencer-intel load fail', e); _data = []; _byNorm = new Map(); return []; }
}

export async function getIntel(opponentName) {
    await load();
    if (!opponentName) return null;
    const norm = normalize(opponentName);
    // Direct hit
    if (_byNorm.has(norm)) return _byNorm.get(norm);
    // Last-name match: take first word of normalized form, find any entry that starts with same last name
    const lastName = norm.split(' ')[0];
    for (const [k, v] of _byNorm.entries()) {
        if (k.startsWith(lastName + ' ')) return v;
    }
    return null;
}

export async function searchIntel(query) {
    await load();
    if (!query || query.length < 2) return [];
    const q = query.toLowerCase().trim();
    return (_data || []).filter(f => f.name.toLowerCase().includes(q)).slice(0, 10);
}

/**
 * Return the national-ranking roster for a profile role.
 *   raedyn → all Y14-ranked fencers sorted by Y14 rank
 *   kaylan → all Y12-ranked fencers sorted by Y12 rank
 * Each entry is the full intel record.
 */
export async function getNationalRoster(role) {
    await load();
    if (!_data) return [];
    const rankKey = role === 'raedyn' ? 'y14' : role === 'kaylan' ? 'y12' : null;
    if (!rankKey) return [];
    return _data
        .filter(f => (f.ranks || {})[rankKey])
        .sort((a, b) => a.ranks[rankKey] - b.ranks[rankKey]);
}

export function getRosterRankKey(role) {
    return role === 'raedyn' ? 'y14' : role === 'kaylan' ? 'y12' : null;
}
