-- Skill rubric content.
--
-- Separated from the 0017 schema because this is the product IP: what
-- beginner/intermediate/advanced actually mean for each skill. Kept in version
-- control rather than living only in the database, so a coach can review and
-- correct it and it can be rebuilt from scratch.

insert into skills (slug, label, category, weapon, summary, prereqs, sort_order) values
    ('en-garde-stance','On-guard stance','footwork','foil','The position everything else is launched from. Bad stance caps every other skill.',array[]::text[],1),
    ('advance-retreat','Advance and retreat','footwork','foil','Moving without telling the opponent you are about to move.',array['en-garde-stance'],2),
    ('lunge','Lunge','footwork','foil','The delivery system for most touches.',array['en-garde-stance'],3),
    ('distance-control','Distance control','distance','foil','Deciding who is close enough to hit. The single highest-leverage skill in foil.',array['advance-retreat'],4),
    ('point-control','Point control','blade','foil','Putting the tip where you aimed, under pressure.',array[]::text[],5),
    ('direct-attack','Direct attack','blade','foil','The simplest scoring action, and the one everything else disguises itself as.',array['lunge','point-control'],6),
    ('disengage','Disengage','blade','foil','Going around the blade when they try to find it.',array['point-control'],7),
    ('beat-attack','Beat attack','blade','foil','Taking the blade out of the way, then hitting.',array['direct-attack'],8),
    ('parry-4','Parry 4','blade','foil','Closing the inside line.',array['en-garde-stance'],9),
    ('parry-6','Parry 6','blade','foil','Closing the outside line.',array['en-garde-stance'],10),
    ('parry-riposte','Parry-riposte','blade','foil','Defence that scores, not defence that survives.',array['parry-4','parry-6'],11),
    ('attack-in-prep','Attack in preparation','tactical','foil','Hitting them while they are still getting ready.',array['distance-control','lunge'],12),
    ('second-intention','Second intention','tactical','foil','Offering an action you expect to fail, to score with the next one.',array['parry-riposte','direct-attack'],13),
    ('bout-composure','Composure under score pressure','mental','foil','Fencing the same way at 14-14 as at 0-0.',array[]::text[],14)
on conflict (slug) do nothing;

insert into skill_levels (skill_slug, level, criteria, common_faults, how_to_train, graduation_test) values
    ('en-garde-stance','beginner',
     'Feet roughly shoulder-width, front foot pointing forward, back foot across. Knees bent. You can hold it for 30 seconds without standing up straight.',
     'Standing too tall. Back knee straight. Feet in a line like a tightrope.',
     'Hold on guard for 30s, three times, in front of a mirror. Fix one thing each round.',
     'Hold a correct on-guard for 60 seconds without your back knee straightening.'),
    ('en-garde-stance','intermediate',
     'Stance survives movement: after five advances and five retreats you are still in the same shape you started in.',
     'Shape collapses as soon as you move. Standing up while retreating.',
     'Advance-retreat the length of the strip, stopping every four steps to check your own position.',
     'Fence a 5-touch bout; a coach or parent watching sees your stance hold on every touch.'),
    ('en-garde-stance','advanced',
     'Stance is invisible to you and adjusts by itself - lower against a taller opponent, more mobile against a runner - without conscious thought.',
     'Using one fixed stance against every opponent.',
     'Bout against three different body types in a session; afterwards write down what your stance changed.',
     'Two coaches independently say your position is never the reason a touch was lost.'),
    ('advance-retreat','beginner',
     'You can advance and retreat without crossing your feet or bouncing, keeping the on-guard shape.',
     'Feet crossing. Bouncing. Front foot landing heel-first, loudly.',
     'Ten advances, ten retreats, slow, listening for quiet feet.',
     'Twenty advances and twenty retreats with no crossed feet and no bouncing.'),
    ('advance-retreat','intermediate',
     'You can change direction instantly - advance to retreat with no pause - and vary step size without losing balance.',
     'A hitch or hop when changing direction. Only one step size.',
     'Partner mirrors you and calls direction changes at random for 60 seconds.',
     'Mirror drill for two minutes; the partner cannot make you stumble or pause.'),
    ('advance-retreat','advanced',
     'Your footwork hides your intention. Opponents cannot tell from your feet whether an attack is coming.',
     'A tell before every attack - a bigger step, a dip, a pause.',
     'Film a minute of bouting. Watch only your feet. Find the tell, then drill without it.',
     'A training partner watching only your feet cannot call your attack better than a coin flip.'),
    ('lunge','beginner',
     'Front foot lands heel-first, back leg straightens, back foot stays flat. You can recover backwards to on guard without using your hands.',
     'Back foot lifting or turning. Leaning forward with the body instead of extending the arm.',
     'Ten slow lunges to a target. Hold the end position for two seconds each.',
     'Ten lunges in a row where the back foot never lifts and you recover unaided every time.'),
    ('lunge','intermediate',
     'Arm extends BEFORE the front foot moves, every time. The lunge reaches a target you could not reach standing.',
     'Foot and hand going together, or the foot first - which loses right of way.',
     'Wall drill: extend, pause, then lunge. Fifty reps, arm always first.',
     'Twenty lunges filmed; the arm leads on all twenty.'),
    ('lunge','advanced',
     'You can lunge from a still position with no preparatory movement, and vary depth to match the distance you are actually at.',
     'One lunge length regardless of distance, so you fall short or crash in.',
     'Partner stands at random distances; you must hit without adjusting your feet first.',
     'Score from three different distances in one bout using three different lunge depths.'),
    ('distance-control','beginner',
     'You know when you are close enough to hit with a lunge, and when you are not.',
     'Attacking from too far and landing short. Standing so close you cannot avoid anything.',
     'No-touch game: stay exactly at lunge distance while your partner moves, for two minutes.',
     'Two minutes of the no-touch game with the coach saying you held distance throughout.'),
    ('distance-control','intermediate',
     'You keep yourself just out of THEIR range while staying in yours, and you break distance when they commit.',
     'Retreating in a straight predictable rhythm they can time.',
     'Bout with a rule: you may only score from the retreat.',
     'Win a 5-touch bout scoring at least three touches after breaking distance.'),
    ('distance-control','advanced',
     'You control the distance so the opponent attacks from where you chose. You can draw an attack on purpose.',
     'Reacting to their distance rather than setting it.',
     'Bout where you must call, before each touch, whether you will draw or pressure.',
     'In a 15-touch bout, correctly predict your own touch pattern on 10 of 15.'),
    ('point-control','beginner',
     'From on guard you can hit a target the size of a fist, standing still, eight times in ten.',
     'Wrist flicking. Whole arm swinging at the target.',
     'Twenty extensions at a small wall target, slow, watching the tip.',
     'Eight of ten hits on a fist-sized target, standing, no lunge.'),
    ('point-control','intermediate',
     'You hit the same target eight of ten while lunging, and can hit high or low line on call.',
     'Point wandering as the lunge accelerates.',
     'Partner calls high or low as you start the lunge. Thirty reps.',
     'Eight of ten on-call high/low hits while lunging.'),
    ('point-control','advanced',
     'Point lands accurately at full speed, off-balance, and around a defending blade.',
     'Only accurate when comfortable and square.',
     'Hit the target from awkward angles: stepping across, half-recovered, blade beaten.',
     'Eight of ten on-target with a partner actively trying to deflect the blade.'),
    ('direct-attack','beginner',
     'You can hit a stationary partner with arm-then-lunge, right of way clearly yours.',
     'Foot before hand. Bending the arm before extending.',
     'Twenty attacks on a still partner, arm always first.',
     'Twenty clean direct attacks, arm leading every time.'),
    ('direct-attack','intermediate',
     'Lands on a partner who is moving and defending, and you choose the moment rather than attacking on a count.',
     'Attacking on a rhythm they can predict.',
     'Partner retreats at random speeds; you pick your moment. Thirty reps.',
     'Land six of ten direct attacks on a retreating, defending partner.'),
    ('direct-attack','advanced',
     'Used as a genuine threat that sets up everything else - opponents respect it enough to react.',
     'So predictable it is only useful as bait.',
     'Bout where the first three touches must be direct attacks, then vary.',
     'Score with a direct attack against an opponent who has already been hit by two.'),
    ('disengage','beginner',
     'You can go around the opponent blade in a small circle and still hit, when they take your blade slowly.',
     'Circle far too big. Losing the target while going around.',
     'Partner takes your blade slowly; you disengage and hit, twenty reps.',
     'Twenty disengages that land, with the tip travelling a small circle.'),
    ('disengage','intermediate',
     'Works at speed and finishes in a lunge, against a partner genuinely searching for the blade.',
     'Disengaging too early, before they commit to taking the blade.',
     'Partner beats or takes the blade at real speed; you disengage. Thirty reps.',
     'Land seven of ten disengages against a partner actively taking the blade.'),
    ('disengage','advanced',
     'You bait the blade take deliberately in order to disengage, and can do it twice in one action.',
     'Only using it reactively, never inviting the take.',
     'Bout rule: offer your blade on purpose, score off their reaction.',
     'Score three touches in a session where you clearly invited the blade take first.'),
    ('beat-attack','beginner',
     'You can knock the opponent blade aside with a short sharp tap and then hit, on a still partner.',
     'Pushing rather than tapping. Beat so hard you lose your own point control.',
     'Twenty beat-then-hit reps on a still partner.',
     'Twenty beat attacks that land, with the beat short and sharp.'),
    ('beat-attack','intermediate',
     'The beat lands on a moving blade and the attack follows immediately in one tempo.',
     'Beat and attack becoming two separate actions with a gap between.',
     'Partner moves the blade; you find it, beat, and finish. Thirty reps.',
     'Seven of ten beat attacks landing on a partner with a moving blade.'),
    ('beat-attack','advanced',
     'You use the beat to provoke a reaction and finish in the line their reaction opens.',
     'Always finishing in the same line after the beat.',
     'Beat, read the reaction, then choose the finish. Bout with this rule only.',
     'Score in two different lines off the same beat in one session.'),
    ('parry-4','beginner',
     'From on guard you can move the blade across to close the inside line without moving your whole arm across your body.',
     'Swinging the whole arm. Parry so wide the riposte cannot come back.',
     'Partner extends slowly at your inside line; you parry twenty times.',
     'Twenty slow parries where the blade is deflected and your point stays near the target line.'),
    ('parry-4','intermediate',
     'The parry works against a real-speed attack and your point stays in a position to riposte immediately.',
     'Parrying late. Parry works but the point ends up pointing at the ceiling.',
     'Partner attacks at increasing speed, one line only, thirty reps.',
     'Deflect eight of ten full-speed attacks to the inside line.'),
    ('parry-4','advanced',
     'You parry 4 without deciding to - it happens on the correct attacks and you are not fooled into it by feints.',
     'Taking the parry every time it is offered, so feints beat you.',
     'Partner mixes real attacks and feints; you may only parry the real ones.',
     'Over twenty mixed actions, parry the real attack and ignore the feint at least sixteen times.'),
    ('parry-6','beginner',
     'You can close the outside line from on guard with a small movement, keeping the point forward.',
     'Over-rotating so the outside line opens completely.',
     'Partner extends slowly to the outside line; twenty parries.',
     'Twenty controlled parries with the point still threatening.'),
    ('parry-6','intermediate',
     'Works at full speed, and you can take it while retreating.',
     'Only works standing still; falls apart when moving backwards.',
     'Retreat-and-parry drill down the strip, twenty reps.',
     'Deflect eight of ten full-speed attacks while retreating.'),
    ('parry-6','advanced',
     'You choose between 4 and 6 correctly under pressure, including against blade actions designed to fool you.',
     'Defaulting to one parry regardless of the line attacked.',
     'Partner attacks both lines at random and disguises which; thirty reps.',
     'Correct parry choice on sixteen of twenty random-line attacks.'),
    ('parry-riposte','beginner',
     'After a successful parry you can extend and hit a stationary partner.',
     'A pause between the parry and the riposte, long enough for them to recover.',
     'Parry then immediately extend, twenty reps, partner stays still.',
     'Twenty parry-ripostes landing on a stationary partner.'),
    ('parry-riposte','intermediate',
     'Parry and riposte read as one motion, and it lands on a partner who is trying to recover.',
     'Riposting to the same target every time, so it gets covered.',
     'Same drill, but the partner attempts to parry your riposte.',
     'Land eight of ten ripostes against a partner actively defending.'),
    ('parry-riposte','advanced',
     'You riposte to whichever line their recovery opens, and it works in a real bout, not just a drill.',
     'Drill-perfect but never used in bouting.',
     'Bout with a rule: you may only score by parry-riposte.',
     'Score at least five touches by parry-riposte across a set of bouts in one session.'),
    ('attack-in-prep','beginner',
     'You can recognise, after the fact, when the opponent was preparing rather than attacking.',
     'Cannot tell preparation from an attack, so you either freeze or counter-attack into a real attack.',
     'Watch a bout video, pause every time the opponent is preparing, and say so out loud.',
     'Correctly identify preparation ten times while watching a bout.'),
    ('attack-in-prep','intermediate',
     'You can hit a partner during their step forward, in a drill where you know it is coming.',
     'Going too early, before their foot commits.',
     'Partner steps forward; you lunge mid-step. Twenty reps, four sets.',
     'Land seven of ten attacks into a known preparation.'),
    ('attack-in-prep','advanced',
     'You take the preparation in a live bout without knowing in advance that it is coming.',
     'Only works when expected; in a bout you never see it in time.',
     'Open bouting with a rule: your first two touches must be attacks in preparation.',
     'Score three touches in preparation across live bouts in one session.'),
    ('second-intention','beginner',
     'You understand and can explain the idea: offer an action you expect to fail, then score with the answer to their answer.',
     'Treating a failed attack as second intention after the fact, rather than planning it.',
     'Talk through three examples with your coach and write them down.',
     'Explain second intention to another fencer using an example from your own bout.'),
    ('second-intention','intermediate',
     'You can execute a planned feint-draw-parry-riposte in a drill where the partner knows their role.',
     'Making the first action too obviously fake, so nobody takes it.',
     'Feint attack, draw their parry, parry their riposte, hit. Twenty reps.',
     'Twenty clean second-intention sequences in drill.'),
    ('second-intention','advanced',
     'You use it in a live bout, chosen because you read a specific opponent habit.',
     'Using it randomly rather than against a habit you have actually noticed.',
     'Scout an opponent for a habit, then plan one second-intention touch around it.',
     'Score a second-intention touch in a live bout and name the habit it exploited.'),
    ('bout-composure','beginner',
     'You can name what happens to you under pressure - rushing, freezing, going quiet.',
     'Not noticing any change, or refusing to admit one.',
     'After each bout write one line: what changed in me when it got close.',
     'Five bouts logged with an honest note about what pressure did to you.'),
    ('bout-composure','intermediate',
     'You have one routine - breath, cue, reset - and you use it between touches when it is tight.',
     'Having a routine but forgetting it exactly when it is needed.',
     'Practise only 14-14 touches. One point, full pressure, then reset.',
     'Use your reset routine on every touch of a close bout, confirmed by someone watching.'),
    ('bout-composure','advanced',
     'Your fencing at 14-14 looks the same on video as at 0-0.',
     'Tightening up and abandoning the actions that got you there.',
     'Film a close bout. Compare your first three and last three touches.',
     'Video shows no change in action variety or tempo between the start and the close of a bout.')
on conflict (skill_slug, level) do nothing;
