// Dashboard — "Today" landing.
// Editorial layout per the new design system: italic greeting, caps-mono labels,
// metric-grid for status, bout-card timeline for recent bouts.

import { el, todayISO, fmtDate, fmtDateLong, daysUntil, toast } from '../lib/util.js';
import { activeProfile } from '../lib/state.js';
import { computeAbilities, recentDailyXp, paceProjection, ABILITIES, ABILITY_META, targetLevelFor, SUMMER_NATIONALS_DATE, daysUntil as daysUntilLevels } from '../lib/levels.js';
import { generateCoachTips } from '../lib/coach-ai.js';
import {
    nextTournament, getPhysicalForDate, getMentalForDate,
    listBouts, listOpponents, listAllProfiles, fetchXpInputs
} from '../lib/db.js';
import { todayCoachCard, listCoachNotes } from '../lib/coach.js';

export async function mountDashboard(root) {
    const profile = activeProfile();
    if (!profile) {
        root.appendChild(el('div', { class: 'empty' }, [
            el('p', { class: 'empty-line' }, ['Pick a profile to begin the day.'])
        ]));
        return;
    }

    const date = todayISO();
    const [nextT, phys, ment, recentBouts, opps] = await Promise.all([
        nextTournament(),
        getPhysicalForDate(date),
        getMentalForDate(date),
        listBouts({ limit: 5 }),
        listOpponents()
    ]);

    // Hero — italic greeting + caps-mono date strip
    const heroSubBits = [el('span', {}, [fmtDateLong(date)])];
    if (nextT) {
        const d = daysUntil(nextT.start_date);
        const tName = nextT.name.length > 22 ? nextT.name.slice(0, 20) + '…' : nextT.name;
        heroSubBits.push(el('span', {}, [
            el('b', {}, [tName]),
            ' · ',
            d === 0 ? 'today' : (d === 1 ? '1 day' : `${d} days`)
        ]));
    }
    root.appendChild(el('div', { class: 'today-hero stagger' }, [
        el('h1', { class: 'today-greeting' }, [
            greeting(), ', ',
            el('span', { class: 'accent' }, [profile.name]),
            '.'
        ]),
        el('div', { class: 'today-sub' }, heroSubBits)
    ]));

    // Status metrics (Body / Mind) — two-column metric grid
    const bodyMetric = phys
        ? {
            val: `${(phys.drills_completed || []).filter((d) => d.done).length}/${(phys.drills_completed || []).length || '–'}`,
            foot: phys.energy_1_10 ? `energy ${phys.energy_1_10}/10` : 'logged'
        }
        : { val: '—', foot: 'no log yet' };
    const mindMetric = ment
        ? {
            val: `${[ment.visualization_done, ment.breathing_done, ment.in_bout_cue_practice].filter(Boolean).length}/3`,
            foot: (ment.scenarios_rehearsed || []).length
                ? `${(ment.scenarios_rehearsed || []).length} scenarios rehearsed`
                : 'logged'
        }
        : { val: '—', foot: 'no log yet' };

    root.appendChild(el('div', { class: 'metric-grid' }, [
        metricCell('TODAY · BODY', bodyMetric.val, bodyMetric.foot, '#physical'),
        metricCell('TODAY · MIND', mindMetric.val, mindMetric.foot, '#mental')
    ]));

    // Level dashboard — gamified XP across both kids
    try {
        const levelSection = await buildLevelDashboard();
        if (levelSection) root.appendChild(levelSection);
    } catch (e) {
        console.warn('Level dashboard skipped:', e);
    }

    // AI Coach training tips — generated from bouts + lessons
    try {
        const coachSection = await buildAICoachSection(profile);
        if (coachSection) root.appendChild(coachSection);
    } catch (e) { console.warn('AI coach skipped:', e); }

    // Coaching card — today's Foil-IQ focus, generated by Claude
    root.appendChild(buildCoachingCard(profile, date));

    // Recent bouts — editorial timeline
    if (recentBouts.length) {
        root.appendChild(el('div', { class: 'label-row', style: { marginTop: '28px' } }, [
            el('span', { class: 'label' }, ['Recent bouts']),
            el('a', { href: '#bouts', class: 'label label-gold', style: { textDecoration: 'none' } }, ['VIEW ALL →'])
        ]));
        for (const b of recentBouts) {
            root.appendChild(boutCard(b));
        }
    } else {
        root.appendChild(el('div', { class: 'empty', style: { marginTop: '20px' } }, [
            el('p', { class: 'empty-line' }, ['Today is quiet. The first bout opens the journal.']),
            el('a', { href: '#bouts/new', class: 'btn btn-primary btn-mono-label empty-cta' }, ['Log a bout'])
        ]));
    }

    // Scout quick-look — small chip row
    if (opps.length) {
        root.appendChild(el('div', { class: 'label-row', style: { marginTop: '28px' } }, [
            el('span', { class: 'label' }, ['Scout · recent']),
            el('a', { href: '#opponents', class: 'label label-gold', style: { textDecoration: 'none' } }, ['VIEW ALL →'])
        ]));
        root.appendChild(el('div', { class: 'chip-row', style: { padding: '0 var(--gut)' } }, opps.slice(0, 6).map((o) =>
            el('a', { href: `#opponents/show?id=${o.id}`, class: 'chip', style: { textDecoration: 'none' } }, [o.name])
        )));
    }

    // Quick log row — at the bottom, restrained
    root.appendChild(el('div', { style: { padding: '32px var(--gut) 16px' } }, [
        el('div', { class: 'label', style: { marginBottom: '14px' } }, ['Quick log']),
        el('div', { style: { display: 'flex', gap: '8px', flexWrap: 'wrap' } }, [
            el('a', { href: '#bouts/new', class: 'btn btn-primary btn-mono-label' }, ['+ Bout']),
            el('a', { href: '#physical', class: 'btn btn-ghost btn-mono-label' }, ['Body']),
            el('a', { href: '#mental', class: 'btn btn-ghost btn-mono-label' }, ['Mind']),
            el('a', { href: '#lessons', class: 'btn btn-ghost btn-mono-label' }, ['Lesson'])
        ])
    ]));

    // Foot — small links to admin areas
    root.appendChild(el('div', { class: 'foil-divider' }));
    root.appendChild(el('div', { style: { display: 'flex', gap: '20px', justifyContent: 'center', padding: '0 var(--gut) 28px' } }, [
        el('a', { href: '#tournaments', class: 'label', style: { textDecoration: 'none' } }, ['Tournaments →']),
        el('a', { href: '#import-v1', class: 'label', style: { textDecoration: 'none' } }, ['Import v1 →'])
    ]));
}

function greeting() {
    const h = new Date().getHours();
    if (h < 12) return 'Good morning';
    if (h < 18) return 'Good afternoon';
    return 'Good evening';
}

function metricCell(label, val, foot, href) {
    return el('a', { href, class: 'metric', style: { textDecoration: 'none', color: 'inherit' } }, [
        el('div', { class: 'metric-label' }, [label]),
        el('div', { class: 'metric-val' }, [val]),
        el('div', { class: 'metric-foot' }, [foot])
    ]);
}

// =====================================================
// Coaching card — Today's Foil-IQ focus, served by Claude
// =====================================================
function buildCoachingCard(profile, date) {
    const wrap = el('section', {
        class: 'coach-card',
        style: {
            margin: '24px var(--gut) 8px', padding: '22px 24px',
            background: 'var(--surface)', borderRadius: 'var(--r-card, 18px)',
            boxShadow: '0 4px 20px rgba(0, 0, 0, 0.04)'
        }
    });

    const head = el('div', {
        style: { display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: '8px' }
    }, [
        el('div', { class: 'metric-label' }, ['Today · coaching card']),
        el('div', { class: 'meta', style: { fontSize: '11px', color: 'var(--ink-mute)' } }, ['by Claude'])
    ]);
    wrap.appendChild(head);

    const body = el('div', { class: 'coach-card-body' });
    wrap.appendChild(body);

    renderEmpty();

    function renderEmpty() {
        body.innerHTML = '';
        body.appendChild(el('p', {
            style: { margin: '6px 0 14px', color: 'var(--ink-mute)', fontStyle: 'italic' }
        }, [`A focus, a warm-up cue, and one drill — tailored to ${profile.name}'s recent pattern.`]));
        body.appendChild(el('button', {
            type: 'button',
            class: 'btn btn-primary',
            onclick: handleGenerate
        }, ['Get today\'s card']));
    }

    function renderLoading() {
        body.innerHTML = '';
        body.appendChild(el('p', {
            style: { margin: '6px 0', color: 'var(--ink-mute)' }
        }, ['Asking Claude. One moment…']));
    }

    function renderResponse(text, model) {
        body.innerHTML = '';
        body.appendChild(el('div', {
            style: { whiteSpace: 'pre-wrap', lineHeight: '1.55', fontSize: '15px', color: 'var(--ink)' }
        }, [text]));
        body.appendChild(el('div', {
            class: 'kicker',
            style: { marginTop: '12px', fontSize: '11px', color: 'var(--ink-mute)' }
        }, [`generated ${new Date().toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })} · ${model || 'claude'}`]));
        body.appendChild(el('div', { style: { marginTop: '12px' } }, [
            el('button', {
                type: 'button',
                class: 'btn btn-ghost btn-sm',
                style: { fontSize: '12px' },
                onclick: handleGenerate
            }, ['Regenerate'])
        ]));
    }

    function renderError(msg) {
        body.innerHTML = '';
        body.appendChild(el('p', { style: { color: 'var(--loss)' } }, ['Could not get coaching card: ' + msg]));
        body.appendChild(el('button', {
            type: 'button',
            class: 'btn btn-ghost btn-sm',
            onclick: handleGenerate
        }, ['Try again']));
    }

    async function handleGenerate() {
        renderLoading();
        try {
            const res = await todayCoachCard();
            if (res?.text) {
                renderResponse(res.text, res.model);
            } else {
                renderError('empty response');
            }
        } catch (e) {
            renderError(e.message || String(e));
        }
    }

    // On mount, look for today's already-generated card and show it without spending a fresh call
    (async () => {
        try {
            const notes = await listCoachNotes({ kind: 'today-coach-card', limit: 1 });
            const latest = notes[0];
            if (latest && latest.created_at?.slice(0, 10) === date) {
                renderResponse(latest.response_text, latest.model);
            }
        } catch (_) { /* ignore — fall through to empty state */ }
    })();

    return wrap;
}

// Render a single bout as the editorial card with sparkline + quote
function boutCard(b) {
    const my = b.my_score ?? 0;
    const their = b.their_score ?? 0;
    const isWin = b.outcome === 'win';
    const isLoss = b.outcome === 'loss';

    // Touch strip — render `their` ghost ticks + `my` scored ticks; if the last
    // scoring action has a 'flick' tag, render the final tick as a flick mark.
    const total = my + their;
    const ticks = [];
    for (let i = 0; i < total; i++) {
        ticks.push(el('span', { class: i < my ? 'touch-tick is-scored' : 'touch-tick' }));
    }
    // Mark the last scored tick as a flick if the action says so
    const acts = Array.isArray(b.scoring_actions) ? b.scoring_actions : [];
    const lastAct = acts.length ? acts[acts.length - 1] : null;
    if (lastAct && /flick/i.test(lastAct.tactic_slug || '') && my > 0) {
        // Replace the last scored tick (the my-th tick at index my-1) with flick
        if (ticks[my - 1]) {
            ticks[my - 1] = el('span', { class: 'touch-tick is-flick' });
        }
    }

    // Tag row — opponent rating + archetypes
    const tags = [];
    if (b.opponent_rating) tags.push(el('span', { class: 'bout-card-opp-tag' }, [b.opponent_rating]));
    (b.opponent_archetypes || []).forEach((a) => tags.push(el('span', { class: 'bout-card-opp-tag' }, [a])));
    if (b.opponent_club) tags.push(el('span', { class: 'bout-card-opp-tag' }, [b.opponent_club]));

    const meta = [];
    meta.push(el('span', {}, [fmtDate(b.date).toUpperCase()]));
    if (b.context) meta.push(el('span', {}, [String(b.context).replace(/_/g, ' ').toUpperCase()]));
    if (b.location) meta.push(el('span', {}, [b.location.toUpperCase()]));

    return el('a', {
        href: `#bouts/show?id=${b.id}`,
        class: 'bout-card',
        style: { textDecoration: 'none', color: 'inherit', display: 'flex' }
    }, [
        el('div', { class: 'bout-card-head' }, [
            el('div', { class: 'bout-card-opp' }, [
                el('div', { class: 'bout-card-opp-name' }, [b.opponent_name || '—']),
                tags.length ? el('div', { class: 'bout-card-opp-tags' }, tags) : null
            ]),
            el('div', { style: { textAlign: 'right' } }, [
                el('div', { class: 'scoreline', style: { justifyContent: 'flex-end' } }, [
                    el('span', { class: `scoreline-num ${isWin ? 'is-win' : (isLoss ? 'is-loss' : '')}` }, [String(my)]),
                    el('span', { class: 'scoreline-sep' }, ['—']),
                    el('span', { class: 'scoreline-num' }, [String(their)])
                ]),
                ticks.length ? el('div', { class: 'touch-strip', style: { justifyContent: 'flex-end' } }, ticks) : null
            ])
        ]),
        b.reflection ? el('div', { class: 'bout-card-quote' }, [b.reflection]) : null,
        meta.length ? el('div', { class: 'bout-card-meta' }, meta) : null
    ]);
}


// =====================================================
// Level dashboard — Strike / Guard / Engine / Mind for both kids
// =====================================================
async function buildLevelDashboard() {
    const allProfiles = await listAllProfiles();
    const kids = allProfiles.filter(p => p.role === 'raedyn' || p.role === 'kaylan');
    if (!kids.length) return null;

    const inputsByKid = await Promise.all(kids.map(p => fetchXpInputs(p.id)));
    const abilitiesByKid = inputsByKid.map(d => computeAbilities(d));
    const recentByKid = inputsByKid.map(d => recentDailyXp(d, 7));

    const days = daysUntilLevels(SUMMER_NATIONALS_DATE);

    const wrap = el('section', { class: 'level-dash stagger' });

    wrap.appendChild(el('div', { class: 'label-row', style: { marginTop: '32px' } }, [
        el('span', { class: 'label' }, ['Progress · Summer Nationals']),
        el('span', { class: 'label label-gold' }, [
            days === 0 ? 'today' : `${days} day${days===1?'':'s'} to go`
        ])
    ]));

    const grid = el('div', { class: 'level-grid' });
    kids.forEach((kid, i) => {
        const abilities = abilitiesByKid[i];
        const recent = recentByKid[i];
        const card = el('div', { class: 'level-card', style: { borderTop: `3px solid ${kid.accent_hex || '#888'}` } }, [
            el('div', { class: 'level-card-head' }, [
                el('span', { class: 'level-name' }, [kid.name]),
                el('span', { class: 'level-tagline' }, ['target by Jul 1'])
            ])
        ]);
        for (const k of ABILITIES) {
            card.appendChild(abilityRow(k, abilities[k], recent[k], days));
        }
        grid.appendChild(card);
    });
    wrap.appendChild(grid);

    return wrap;
}

function abilityRow(key, ability, dailyXp, days) {
    const meta = ABILITY_META[key];
    const target = targetLevelFor(key);
    const pace = paceProjection(ability, dailyXp || 0, target, days);
    const paceIcon =
        pace.status === 'done'        ? '🏆' :
        pace.status === 'not_started' ? '🚀' :
        pace.status === 'on_track'    ? '🟢' :
        pace.status === 'close'       ? '🟡' : '🔴';
    const paceText =
        pace.status === 'done'        ? `MAX · target Lv ${target}` :
        pace.status === 'not_started' ? `Get started! target Lv ${target}` :
        pace.status === 'on_track'    ? `on pace · ~${Math.round(dailyXp)} XP/day` :
        pace.status === 'close'       ? `close · ${pace.xpPerDayNeeded}/day to Lv ${target}` :
                                        `${pace.xpPerDayNeeded}/day to Lv ${target}`;
    return el('div', { class: `ability-row tier-${ability.rank.tier}` }, [
        el('div', { class: 'ability-head' }, [
            el('span', { class: 'ability-icon' }, [meta.icon]),
            el('span', { class: 'ability-label' }, [meta.label.toUpperCase()]),
            el('span', { class: 'ability-level', style: { color: ability.rank.color } }, [
                'Lv ', String(ability.level)
            ])
        ]),
        el('div', { class: 'ability-bar' }, [
            el('div', {
                class: 'ability-fill',
                style: { width: ability.pctToNext + '%', background: ability.rank.color }
            })
        ]),
        el('div', { class: 'ability-foot' }, [
            el('span', { class: 'ability-xp' }, [
                String(ability.xpToNext), ' / 100 XP'
            ]),
            el('span', { class: 'ability-pace' }, [paceIcon + ' ' + paceText])
        ])
    ]);
}


// =====================================================
// AI Coach — quantified training tips for the active profile
// =====================================================
async function buildAICoachSection(profile) {
    const data = await fetchXpInputs(profile.id);
    const result = generateCoachTips(data);
    if (!result.tips.length && !result.reminders.length) return null;

    const wrap = el('section', { class: 'coach-tips stagger', style: { padding: '0 var(--gut)', marginTop: '28px' } });
    wrap.appendChild(el('div', { class: 'label-row' }, [
        el('span', { class: 'label' }, ['AI Coach · Train These']),
        el('span', { class: 'label label-gold' }, [
            result.weeklyXpForecast > 0 ? `+${result.weeklyXpForecast} XP / week if you follow it` : `${result.boutCount} bouts analyzed`
        ])
    ]));

    for (const tip of result.tips) {
        wrap.appendChild(coachTipCard(tip));
    }
    for (const r of result.reminders) {
        wrap.appendChild(el('div', { class: 'coach-reminder' }, [r]));
    }
    return wrap;
}

function coachTipCard(tip) {
    const card = el('div', { class: `coach-tip coach-tip-p${tip.priority}` });
    card.appendChild(el('div', { class: 'coach-tip-label' }, [
        '#' + tip.priority + ' · ' + tip.label
    ]));
    card.appendChild(el('div', { class: 'coach-tip-title' }, [tip.title]));
    if (tip.from)       card.appendChild(el('div', { class: 'coach-tip-meta' }, [`from ${tip.from} · mastery ${tip.mastery ?? '?'}/10`]));
    if (tip.diagnosis)  card.appendChild(el('div', { class: 'coach-tip-meta' }, [tip.diagnosis]));
    if (tip.coachQuote) card.appendChild(el('blockquote', { class: 'coach-quote' }, [`"${tip.coachQuote}"`]));

    if (tip.drill) {
        const d = tip.drill;
        card.appendChild(el('div', { class: 'coach-drill' }, [
            el('div', { class: 'coach-drill-name' }, [d.name]),
            el('div', { class: 'coach-drill-prescription' }, [
                el('span', {}, [`${d.reps} reps`]),
                el('span', { class: 'sep' }, ['·']),
                el('span', {}, [`${d.sets} sets`]),
                el('span', { class: 'sep' }, ['·']),
                el('span', {}, [`${d.restSec}s rest`]),
                el('span', { class: 'sep' }, ['·']),
                el('span', {}, [d.frequency]),
                el('span', { class: 'sep' }, ['·']),
                el('span', { class: 'xp-badge' }, [`+${d.xpPerSession} XP/session  ⚡ +${d.xpPerWeek}/week`])
            ])
        ]));
    }
    if (tip.why) card.appendChild(el('div', { class: 'coach-why' }, [`Why: ${tip.why}`]));
    return card;
}
